# Generated by Django 6.0.1 on 2026-03-10 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='category.productvariant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.productvariant'),
        ),
    ]
