# Generated by Django 6.0.1 on 2026-03-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_cartitem_variant_orderitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_reduced',
            field=models.BooleanField(default=False),
        ),
    ]
