# Generated by Django 6.0.2 on 2026-02-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_order_discount_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_applied',
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
