# Generated by Django 6.0.1 on 2026-03-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_order_stock_reduced'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.IntegerField(default=0),
        ),
    ]
