# Generated by Django 6.0.2 on 2026-02-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_product_subcategory_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subcategory_images/'),
        ),
    ]
