# Generated by Django 6.0.1 on 2026-02-27 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_review'),
        ('category', '0003_remove_order_discount_applied_order_discount_amount'),
    ]

    operations = [
    ]
