# Generated by Django 6.0.2 on 2026-03-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_returnrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Placed', max_length=20),
        ),
    ]
