# Generated by Django 6.0.1 on 2026-03-01 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_merge_20260227_1100'),
        ('category', '0005_alter_order_status'),
    ]

    operations = [
    ]
