# Generated by Django 6.0.1 on 2026-03-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_address_country_code_address_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
