# Generated by Django 6.0.1 on 2026-03-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_recentlyviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coins_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='coins_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
