# Generated by Django 6.0.1 on 2026-03-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_order_coins_added_order_coins_used_product_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
